import { Metadata } from 'next';

export const metadata: Metadata = {
	title: {
		absolute: '',
		default: 'Next.js - Tutorial',
		template: '%s - Tutorial',
	},
	description: 'Generated by Next.js',
}

type Props = {
	children: React.ReactNode,
}

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
			<body>
				<header
					style={{
						backgroundColor: 'lightblue',
						padding: '1rem',
					}}
				>
					<p>Header</p>
				</header>
				{children}
				<footer
					style={{
						backgroundColor: 'ghostwhite',
						padding: '1rem',
					}}
				>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
};
